2022-03-06 20:23:02,789 (67872/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-03-06 20:23:02,789 (67872/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-06 20:23:02,792 (67872/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2022-03-06 20:25:50,267 (68376/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-03-06 20:25:50,268 (68376/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-06 20:27:05,518 (68376/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "winstep-app-dev.catz1cehyexe.us-east-1.rds.amazonaws.com" (172.31.13.235), port 5432 failed: Operation timed out\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-03-06 20:28:24,927 (69322/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-03-06 20:28:24,928 (69322/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-06 20:29:39,961 (69322/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "winstep-app-dev.catz1cehyexe.us-east-1.rds.amazonaws.com" (172.31.13.235), port 5432 failed: Operation timed out\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-03-06 20:32:54,703 (69804/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-03-06 20:32:54,703 (69804/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-06 20:34:09,720 (69804/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "winstep-app-dev.catz1cehyexe.us-east-1.rds.amazonaws.com" (172.31.13.235), port 5432 failed: Operation timed out\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-03-06 20:43:50,452 (76502/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-03-06 20:43:50,453 (76502/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-06 20:45:05,483 (76502/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "winstep-app-dev.catz1cehyexe.us-east-1.rds.amazonaws.com" (54.227.167.14), port 5432 failed: Operation timed out\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
